### ISSUE TITLE
how to pass request object for Fetch API in webworker

### ISSUE THREAD

**Issue by rshashik** [deebloo/things-you-can-do-in-a-web-worker#14]
Hi ,
I have the requirement to take a Request Object from the user with all the data required to make a fetch request, i need to pass the Request Object to webworker and then do the actual fetch inside webworker. whats the best way to pass request parameters in post message function??

**main.js:**
```JS
const myRequest = new Request('flowers.jpg', {
  method: 'GET',
  headers: myHeaders,
  mode: 'cors',
  cache: 'default',
});

getData(myRequest);

function getData(myRequest){
  myWorker = new Worker(script_url);
  postmessage(JSON.stringify(myRequest))
}
</script>
```

**webworker.js:**
```JS
onmessage(e){
response=fetch(e.data.requestObject)
postmessage(response)
}
```
Issue: JSON.Stringify(requestObject) is returning empty object. If we dont stringify the request object then its throwing 

> Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': Request object could not be cloned.

What is  the best way to pass fetcher function from main.js to worker.js file??

**Comment by deebloo** [comment]
@rshashik hey there! can you format your code example to make it easier to read? ultimately any data you pass to and from a web worker has to adhere to "[structured cloning](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)". All this means is that you can only pass data back and forth, so think something that is valid JSON or primitives like numbers and strings. 

If I understand your example you won't be able to pass the `Request` object to the worker. What I would do is pass the data you need to the worker via postMessage and construct a new `Request` object in the worker itself.

**Comment by deebloo** [comment]
also make sure you are calling `postMessage` on your webworker itself in main.js

**Comment by rshashik** [comment]
@deebloo I will try your suggestion. Thank you for replying so quickly !!

**Comment by deebloo** [comment]
@rshashik sure thing let me know if you need help with anything else. Only other thing I will say is don't create a new worker for each get request. create a single one and send multiple messages to it.

**Comment by rshashik** [comment]
Hi ,

I published my first JS library, i need your help to configure webpack and
package it properly so that we can expose public functions properly.

Please let me know whenever you are available.  Iam from India. We can
connect in skype/zoom.

https://github.com/rshashik/ui-security

Thanks
Raghav
